name: Deploy NestJS (No Docker)

on:
  push:
    branches: [ main ]

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build

  cd-deploy:
    needs: ci-build
    runs-on: ubuntu-latest
    steps:
    # We only need 'dist', 'package.json', and 'package-lock.json' on the server
      - name: Deploy to EC2 via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/,package.json,package-lock.json"
          target: "~/apps/my-nestjs-app"

      - name: Restart Application via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/my-nestjs-app
            npm install --omit=dev # Only install production dependencies on EC2
            
            # Start or Reload the app with PM2
            pm2 delete nest-api || true
            pm2 start dist/main.js --name nest-api